import { StyleSheet, Dimensions, Platform, StatusBar } from "react-native";
import ThemeColors from "../../../theme/colors";

const { Colors, Theme } = ThemeColors;
const { width: screenWidth } = Dimensions.get("window");

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  scrollContent: {
    paddingBottom: 0,
  },
  headerSection: {
    position: 'relative',
    zIndex: 1,
  },
  topOrangeBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 140,
    backgroundColor: '#FF8B47',
    zIndex: -1,
  },
  // Header
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 40,
    paddingBottom: 12,
    zIndex: 1,
  },
  brandTitle: {
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 2,
    color: '#FFFFFF',
  },
  menuBtn: {
    padding: 8,
  },
  profileBtn: {
    padding: 4,
  },
  profileImg: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  cartBtn: {
    padding: 0,
    position: "relative",
  },
  cartBackdrop: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: "#FF3B30",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 2,
  },
  cartBadgeText: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "700",
  },
  // Search Section
  searchSection: {
    paddingHorizontal: 16,
    marginBottom: 16,
    zIndex: 1,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 22,
    paddingHorizontal: 14,
    height: 44,
    borderWidth: 0,
    flex: 1,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    color: "#1A1A1A",
    fontSize: 15,
  },
  searchPlaceholder: {
    flex: 1,
    marginLeft: 10,
    color: "#666666",
    fontSize: 15,
  },
  micBtn: {
    paddingLeft: 8,
    paddingVertical: 4,
  },
  filterBtn: {
    width: 44,
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  // Hero Section
  heroSection: {
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  heroShapes: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  heroCircleOne: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: '#FFF1E8',
    top: -40,
    right: -30,
  },
  heroCircleTwo: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#FFE1CF',
    bottom: -30,
    left: -20,
  },
  heroCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#EAEAEA',
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A1A1A',
    marginBottom: 6,
  },
  heroSubtitle: {
    fontSize: 13,
    color: '#666666',
    marginBottom: 12,
    fontWeight: '600',
  },
  heroButtonsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroPrimaryBtn: {
    backgroundColor: '#FF8B47',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    marginRight: 10,
  },
  heroBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  heroSecondaryBtn: {
    backgroundColor: '#FFF5F0',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
  },
  heroBtnSecondaryText: {
    color: '#FF8B47',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  // Featured Collections
  featuredSection: {
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  featuredList: {
    paddingRight: 16,
  },
  featuredCard: {
    width: 180,
    height: 120,
    borderRadius: 14,
    overflow: 'hidden',
    marginRight: 12,
    backgroundColor: '#F2F2F2',
  },
  featuredImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  featuredOverlay: {
    ...Platform.select({
      ios: { position: 'absolute' },
      android: { position: 'absolute' },
      default: { position: 'absolute' }
    }),
    left: 0,
    right: 0,
    bottom: 0,
    top: 0,
    backgroundColor: 'rgba(0,0,0,0.15)'
  },
  featuredTextWrap: {
    position: 'absolute',
    left: 10,
    bottom: 10,
  },
  featuredTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
    marginBottom: 2,
  },
  featuredSubtitle: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 12,
    fontWeight: '600',
  },
  // Quick Actions
  quickActionsSection: {
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  quickActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  quickActionItem: {
    flex: 1,
    marginRight: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  quickActionIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFF5F0',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  quickActionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  // Remove right margin on last quick action
  quickActionItemLast: {
    marginRight: 0,
  },
  // Promo Card
  promoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 14,
    backgroundColor: '#1A1A1A',
  },
  promoTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  promoSubtitle: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    fontWeight: '500',
  },
  promoButton: {
    backgroundColor: '#FF8B47',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
    marginLeft: 12,
  },
  promoButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  // Categories Section
  categoriesSection: {
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  categoriesContainer: {
    paddingRight: 16,
  },
  categoryBtn: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  categoryBtnActive: {
    backgroundColor: "#FF8B47",
    borderColor: "#FF8B47",
  },
  categoryText: {
    fontSize: 13,
    fontWeight: "500",
    color: "#1A1A1A",
  },
  categoryTextActive: {
    color: "#FFFFFF",
  },
  // Banner Carousel
  bannerCarousel: {
    paddingHorizontal: 16,
    marginTop: 4,
    marginBottom: 16,
  },
  bannerContent: {
    paddingRight: 0,
  },
  bannerCard: {
    width: screenWidth - 32, // full width minus 16px padding on each side
    borderRadius: 16,
    overflow: 'hidden',
  },
  bannerImage: {
    width: '100%',
    height: 200,
    resizeMode: 'cover',
  },
  bannerOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.12)'
  },
  bannerCaptionWrap: {
    position: 'absolute',
    left: 16,
    bottom: 16,
  },
  bannerCaptionTitle: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 18,
  },
  bannerCaptionSubtitle: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 13,
    marginTop: 2,
  },
  // Banner Pagination Dots
  dotsContainer: {
    position: 'absolute',
    bottom: 10,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.5)',
    marginHorizontal: 3,
  },
  dotActive: {
    width: 16,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
  // Products Section
  productsSection: {
    paddingHorizontal: 16,
    paddingBottom: 0,
    marginBottom: 0,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  seeAllButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: "#FFF5F0",
  },
  seeAllText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#FF8B47",
    marginRight: 4,
  },
  // Products
  productRow: {
    justifyContent: "space-between",
    marginBottom: 12,
  },
  productCard: {
    width: (screenWidth - 16 * 2 - 12) / 2,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    marginBottom: 12,
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 1,
  },
  productImg: {
    width: "100%",
    height: 140,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    resizeMode: "cover",
  },
  productInfo: {
    padding: 10,
  },
  productName: {
    fontSize: 13,
    fontWeight: "500",
    color: "#1A1A1A",
    marginBottom: 2,
  },
  productPrice: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FF8B47",
  },
  productSeller: {
    fontSize: 11,
    fontWeight: "400",
    color: "#666666",
    marginTop: 2,
    fontStyle: 'italic',
  },
  favoriteBtn: {
    position: "absolute",
    top: 6,
    right: 6,
    zIndex: 10,
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    borderRadius: 14,
    width: 26,
    height: 26,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.12,
    shadowRadius: 2,
    elevation: 1,
  },
  addToCartBtn: {
    position: "absolute",
    bottom: 10,
    right: 10,
    zIndex: 10,
    backgroundColor: "#FF8B47",
    borderRadius: 18,
    width: 36,
    height: 36,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 3,
    elevation: 2,
  },
  shopsSection: {
    paddingHorizontal: 16,
    marginBottom: 16,
    marginTop: 8,
  },
  shopsRow: {
    paddingRight: 16,
    paddingVertical: 8,
  },
  shopItem: {
    alignItems: 'center',
    marginRight: 20,
    width: 80,
  },
  shopAvatarContainer: {
    marginBottom: 10,
    position: 'relative',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  shopAvatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#F8FAFC',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  shopAvatarPlaceholder: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#FFF7ED',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  shopName: {
    fontSize: 13,
    color: '#1E293B',
    fontWeight: '600',
    textAlign: 'center',
    width: 80,
    lineHeight: 16,
    marginTop: 2,
  },
  shopDescription: {
    fontSize: 10,
    color: '#64748B',
    textAlign: 'center',
    width: 80,
    lineHeight: 12,
    marginTop: 2,
  },

  // Shops Loading and Empty States
  shopsLoadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  shopsLoadingText: {
    fontSize: 14,
    color: '#666666',
    marginTop: 8,
  },
  noShopsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  noShopsText: {
    fontSize: 14,
    color: '#CCCCCC',
    marginTop: 8,
    textAlign: 'center',
  },

  // Loading, Error, and Empty States
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#666666',
    fontWeight: '500',
  },
  errorContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  errorText: {
    marginTop: 12,
    fontSize: 16,
    color: '#FF6B6B',
    fontWeight: '600',
  },
  retryButton: {
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#FF8B47',
    borderRadius: 8,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    marginTop: 12,
    fontSize: 16,
    color: '#999999',
    fontWeight: '600',
  },
  emptySubtext: {
    marginTop: 4,
    fontSize: 14,
    color: '#CCCCCC',
    textAlign: 'center',
  },
});
